### ISSUE TITLE
Support external banner messages

### ISSUE THREAD

**Issue by adam-collins** [AtlasOfLivingAustralia/species-lists#89]
Single page applications need a mechanism for displaying banner messages. For other ALA applications the ala-admin-plugin is used to set a message and severity.

Task 
- Display an externally defined banner message.

For testing use https://www-test.ala.org.au/status.json. This is managed in [home-static](https://github.com/AtlasOfLivingAustralia/home-static).

It has
- a global message
- application specific messages, "species-lists"
- test messages

Properties are
- "message", the html message. Can be empty.
- "severity", one of INFO, WARNING, DANGER. 
- "updated", date/time to be used if the message is dismissible. e.g. is dismissible for the rest of the day.

The inclusion of messages for other applications provides for the ability to display dependency messages in context. Additional applications will be added as they are converted to single page or when there is a dependency message requirement.

The use of a single status.json for all applications is not mandatory, but is the starting point.

Partial bootstrap css in use for severity; alert-info, alert-warning, alert-danger
```css
.alert-info {
    color: #31708f;
    background-color: #d9edf7;
    border-color: #bce8f1
}

.alert-info hr {
    border-top-color: #a6e1ec
}

.alert-info .alert-link {
    color: #245269
}

.alert-warning {
    color: #8a6d3b;
    background-color: #fcf8e3;
    border-color: #faebcc
}

.alert-warning hr {
    border-top-color: #f7e1b5
}

.alert-warning .alert-link {
    color: #66512c
}

.alert-danger {
    color: #a94442;
    background-color: #f2dede;
    border-color: #ebccd1
}

.alert-danger hr {
    border-top-color: #e4b9c0
}

.alert-danger .alert-link {
    color: #843534
}
```
